apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: hydra-job-1234@foo-bar-1234.iam.gserviceaccount.com
  name: hydra-job-sa
